[[redirects]]
  from = "/search"
  to = "https://api.yelp.com/v3/businesses"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"